package com.safeminds.watch.sessionTransfer

enum class DataTransferStatus {
    // THIS CLASS SHOWS THE STATE OF TRANSFERRING PROCESS
    WAITING, // DATA IS READY BUT NOT SENT TO THE PHONE YET
    IN_PROGRESS, // SENDING DATA IS CURRENTLY IS PROGRESS
    SUCCESS, // DATA IS SUCCESSFULLY SENT TO THE PHONE
    FAILED // DATA IS FAILED TO SENT AFTER NUMBER OF RETRIES
}